### ISSUE TITLE
你好，请问为什么归档页面无法显示

### ISSUE THREAD

**Issue by zzpw** [blinkfox/hexo-theme-matery#200]
hexo g 之后会报错，报错的内容如下，然后在本地服务器上点归档按钮无法打开。

ERROR Render HTML failed: archives/index.html
SyntaxError: Invalid or unexpected token in "D:\\hexo\\themes\\hexo-theme-matery\\layout\\archive.ejs"
    at new Function (<anonymous>)
    at exports.compile (D:\hexo\node_modules\hexo-renderer-mathjax\node_modules\ejs\lib\ejs.js:242:14)
    at Object.exports.render (D:\hexo\node_modules\hexo-renderer-mathjax\node_modules\ejs\lib\ejs.js:284:66)
    at Hexo.<anonymous> (D:\hexo\node_modules\hexo-renderer-mathjax\index.js:14:24)
    at Hexo.tryCatcher (D:\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.ret (eval at makeNodePromisifiedEval (E:\Node.js\node_global\node_modules\hexo\node_modules\bluebird\js\release\promisify.js:184:12), <anonymous>:13:39)
    at Promise.then.text (D:\hexo\node_modules\hexo\lib\hexo\render.js:60:20)
    at tryCatcher (D:\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\hexo\node_modules\bluebird\js\release\promise.js:517:31)
    at Promise._settlePromise (D:\hexo\node_modules\bluebird\js\release\promise.js:574:18)
    at Promise._settlePromiseCtx (D:\hexo\node_modules\bluebird\js\release\promise.js:611:10)
    at _drainQueueStep (D:\hexo\node_modules\bluebird\js\release\async.js:142:12)
    at _drainQueue (D:\hexo\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (D:\hexo\node_modules\bluebird\js\release\async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (D:\hexo\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)

**Comment by zzpw** [comment]
在issues里找到方法了，打扰了

**Comment by levi5611** [comment]
怎么解决的啊请问？

**Comment by zzpw** [comment]
> 怎么解决的啊请问？

@levi5611 
我当时是按照这个 issue 里，删掉了几行注释解决的，不知现在是否还适用。
https://github.com/blinkfox/hexo-theme-matery/issues/72

**Comment by levi5611** [comment]
> > 怎么解决的啊请问？
> 
> 我当时是按照这个 issue 里，删掉了几行注释解决的，不知现在是否还适用。 #72

非常感谢，按照这个方法我也解决了！（感谢如此迅速的恢复）
