### ISSUE TITLE
新建的文章 为什么打不开？报错如下

### ISSUE THREAD

**Issue by AIrobot6** [blinkfox/hexo-theme-matery#241]
Unhandled rejection ReferenceError: D:\ok\themes\hexo-theme-matery\layout\post.ejs:26
    24|
    25|     <% if (isTocEnable) { %>
 >> 26|     <%- partial('_partial/post-detail-toc.ejs') %>
    27|     <% } else { %>
    28|     <%- partial('_partial/post-detail.ejs') %>
    29|     <% } %>

D:\ok\themes\hexo-theme-matery\layout\_partial\post-detail-toc.ejs:90
    88| <div class="row">
    89|     <div id="main-content" class="col s12 m12 l9">
 >> 90|         <%- partial('_partial/post-detail.ejs') %>
    91|     </div>
    92|     <div id="toc-aside" class="expanded col l3 hide-on-med-and-down">
    93|         <div class="toc-widget">

D:\ok\themes\hexo-theme-matery\layout\_partial\post-detail.ejs:53
    51|                 <div class="info-break-policy">
    52|                     <i class="far fa-file-word fa-fw"></i><%- __('wordCount') %>:&nbsp;&nbsp;
 >> 53|                     <%= wordcount(page.content) %>
    54|                 </div>
    55|                 <% } %>
    56|

wordcount is not defined
    at eval (D:\ok\themes\hexo-theme-matery\layout\_partial\post-detail.ejs:84:7)
    at post-detail (D:\ok\node_modules\ejs\lib\ejs.js:682:17)
    at Theme._View.View._compiledSync (D:\ok\node_modules\hexo\lib\theme\view.js:119:22)
    at Theme._View.View.View.renderSync (D:\ok\node_modules\hexo\lib\theme\view.js:48:23)
    at Object.partial (D:\ok\node_modules\hexo\lib\plugins\helper\partial.js:34:15)
    at eval (D:\ok\themes\hexo-theme-matery\layout\_partial\post-detail-toc.ejs:14:17)
    at post-detail-toc (D:\ok\node_modules\ejs\lib\ejs.js:682:17)
    at Theme._View.View._compiledSync (D:\ok\node_modules\hexo\lib\theme\view.js:119:22)
    at Theme._View.View.View.renderSync (D:\ok\node_modules\hexo\lib\theme\view.js:48:23)
    at Object.partial (D:\ok\node_modules\hexo\lib\plugins\helper\partial.js:34:15)
    at eval (D:\ok\themes\hexo-theme-matery\layout\post.ejs:47:17)
    at post (D:\ok\node_modules\ejs\lib\ejs.js:682:17)
    at Theme._View.View._compiled (D:\ok\node_modules\hexo\lib\theme\view.js:123:48)
    at Theme._View.View.View.render (D:\ok\node_modules\hexo\lib\theme\view.js:29:15)
    at D:\ok\node_modules\hexo\lib\hexo\index.js:365:21
    at tryCatcher (D:\ok\node_modules\bluebird\js\release\util.js:16:23)
    at D:\ok\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (D:\ok\node_modules\hexo\lib\hexo\router.js:123:3)
    at RouteStream.Readable.read (_stream_readable.js:490:10)
    at resume_ (_stream_readable.js:975:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

**Comment by blinkfox** [comment]
应该需要安装 `hexo-wordcount` 插件。

**Comment by blinkfox** [comment]
新版本 `v1.2.2` 已经做了些判断，不安装 `hexo-wordcount` 应该也不会报错了。
