### ISSUE TITLE
wordcount is not defined 文章字数统计和阅读时长统计开启都会报错

### ISSUE THREAD

**Issue by Yuimm** [blinkfox/hexo-theme-matery#391]
Unhandled rejection ReferenceError: E:\Git\Blog\themes\matery\layout\post.ejs:26
    24|
    25|     <% if (isTocEnable) { %>
 >> 26|     <%- partial('_partial/post-detail-toc.ejs') %>
    27|     <% } else { %>
    28|     <%- partial('_partial/post-detail.ejs') %>
    29|     <% } %>

E:\Git\Blog\themes\matery\layout\_partial\post-detail-toc.ejs:96
    94| <div class="row">
    95|     <div id="main-content" class="col s12 m12 l9">
 >> 96|         <%- partial('_partial/post-detail.ejs') %>
    97|     </div>
    98|     <div id="toc-aside" class="expanded col l3 hide-on-med-and-down">
    99|         <div class="toc-widget">

E:\Git\Blog\themes\matery\layout\_partial\post-detail.ejs:53
    51|                 <div class="info-break-policy">
    52|                     <i class="far fa-file-word fa-fw"></i><%- __('wordCount') %>:&nbsp;&nbsp;
 >> 53|                     <%= wordcount(page.content) %>
    54|                 </div>
    55|                 <% } %>
    56|

wordcount is not defined
    at eval (E:\Git\Blog\themes\matery\layout\_partial\post-detail.ejs:82:7)
    at post-detail (E:\Git\Blog\node_modules\ejs\lib\ejs.js:682:17)
    at viewFn._compiledSync (E:\Git\Blog\node_modules\hexo\lib\theme\view.js:132:22)
    at viewFn.View.renderSync (E:\Git\Blog\node_modules\hexo\lib\theme\view.js:60:23)
    at Object.partial (E:\Git\Blog\node_modules\hexo\lib\plugins\helper\partial.js:34:15)
    at eval (E:\Git\Blog\themes\matery\layout\_partial\post-detail-toc.ejs:12:17)
    at post-detail-toc (E:\Git\Blog\node_modules\ejs\lib\ejs.js:682:17)
    at viewFn._compiledSync (E:\Git\Blog\node_modules\hexo\lib\theme\view.js:132:22)
    at viewFn.View.renderSync (E:\Git\Blog\node_modules\hexo\lib\theme\view.js:60:23)
    at Object.partial (E:\Git\Blog\node_modules\hexo\lib\plugins\helper\partial.js:34:15)
    at eval (E:\Git\Blog\themes\matery\layout\post.ejs:45:17)
    at post (E:\Git\Blog\node_modules\ejs\lib\ejs.js:682:17)
    at viewFn._compiled (E:\Git\Blog\node_modules\hexo\lib\theme\view.js:136:48)
    at viewFn.View.render (E:\Git\Blog\node_modules\hexo\lib\theme\view.js:41:15)
    at E:\Git\Blog\node_modules\hexo\lib\hexo\index.js:61:21
    at tryCatcher (E:\Git\Blog\node_modules\bluebird\js\release\util.js:16:23)
    at E:\Git\Blog\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (E:\Git\Blog\node_modules\hexo\lib\hexo\router.js:126:3)
    at RouteStream.Readable.read (_stream_readable.js:478:10)
    at resume_ (_stream_readable.js:965:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Unhandled rejection ReferenceError: E:\Git\Blog\themes\matery\layout\post.ejs:26
    24|
    25|     <% if (isTocEnable) { %>
 >> 26|     <%- partial('_partial/post-detail-toc.ejs') %>
    27|     <% } else { %>
    28|     <%- partial('_partial/post-detail.ejs') %>
    29|     <% } %>

E:\Git\Blog\themes\matery\layout\_partial\post-detail-toc.ejs:96
    94| <div class="row">
    95|     <div id="main-content" class="col s12 m12 l9">
 >> 96|         <%- partial('_partial/post-detail.ejs') %>
    97|     </div>
    98|     <div id="toc-aside" class="expanded col l3 hide-on-med-and-down">
    99|         <div class="toc-widget">

E:\Git\Blog\themes\matery\layout\_partial\post-detail.ejs:53
    51|                 <div class="info-break-policy">
    52|                     <i class="far fa-file-word fa-fw"></i><%- __('wordCount') %>:&nbsp;&nbsp;
 >> 53|                     <%= wordcount(page.content) %>
    54|                 </div>
    55|                 <% } %>
    56|

wordcount is not defined
    at eval (E:\Git\Blog\themes\matery\layout\_partial\post-detail.ejs:82:7)
    at post-detail (E:\Git\Blog\node_modules\ejs\lib\ejs.js:682:17)
    at viewFn._compiledSync (E:\Git\Blog\node_modules\hexo\lib\theme\view.js:132:22)
    at viewFn.View.renderSync (E:\Git\Blog\node_modules\hexo\lib\theme\view.js:60:23)
    at Object.partial (E:\Git\Blog\node_modules\hexo\lib\plugins\helper\partial.js:34:15)
    at eval (E:\Git\Blog\themes\matery\layout\_partial\post-detail-toc.ejs:12:17)
    at post-detail-toc (E:\Git\Blog\node_modules\ejs\lib\ejs.js:682:17)
    at viewFn._compiledSync (E:\Git\Blog\node_modules\hexo\lib\theme\view.js:132:22)
    at viewFn.View.renderSync (E:\Git\Blog\node_modules\hexo\lib\theme\view.js:60:23)
    at Object.partial (E:\Git\Blog\node_modules\hexo\lib\plugins\helper\partial.js:34:15)
    at eval (E:\Git\Blog\themes\matery\layout\post.ejs:45:17)
    at post (E:\Git\Blog\node_modules\ejs\lib\ejs.js:682:17)
    at viewFn._compiled (E:\Git\Blog\node_modules\hexo\lib\theme\view.js:136:48)
    at viewFn.View.render (E:\Git\Blog\node_modules\hexo\lib\theme\view.js:41:15)
    at E:\Git\Blog\node_modules\hexo\lib\hexo\index.js:61:21
    at tryCatcher (E:\Git\Blog\node_modules\bluebird\js\release\util.js:16:23)
    at E:\Git\Blog\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (E:\Git\Blog\node_modules\hexo\lib\hexo\router.js:126:3)
    at RouteStream.Readable.read (_stream_readable.js:478:10)
    at resume_ (_stream_readable.js:965:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

**Comment by cytsese** [comment]
一样问题，而且配置改回去后也还是报错
