### ISSUE TITLE
git clone最新版代码后，报了以下错误，可以告知原因或解决办法吗？

### ISSUE THREAD

**Issue by ZhenzongGu** [blinkfox/hexo-theme-matery#887]
TypeError: /home/digga/Documents/site/themes/matery/layout/archive.ejs:1
 >> 1| <%- partial('_partial/bg-cover') %>
    2| 
    3| <main class="content">
    4| 

/home/digga/Documents/site/themes/matery/layout/_partial/bg-cover.ejs:3
    1| <div class="bg-cover pd-header about-cover">
    2|     <div class="container">
 >> 3|     <%- partial('_partial/bg-cover-content') %>
    4|     </div>
    5| </div>

/home/digga/Documents/site/themes/matery/layout/_partial/bg-cover-content.ejs:46
    44| <script>
    45|     <% if (theme.banner.enable && theme.banner.random) { %>
 >> 46|       var bannerUrl = "<%- theme.cdn.url %><%- url_for('/medias/featureimages/') %>" + Math.floor(Math.random() * <%- theme.featureImages.length %>) + '.jpg';
    47|     <% } else { %>
    48|       // 每天切换 banner 图.  Switch banner image every day.
    49|       var bannerUrl = "<%- theme.cdn.url %><%- url_for('/medias/banner/') %>" + new Date().getDay() + '.jpg';

Cannot read properties of undefined (reading 'url')
    at eval ("/home/digga/Documents/site/themes/matery/layout/_partial/bg-cover-content.ejs":74:27)
    at bg-cover-content (/home/digga/Documents/site/node_modules/ejs/lib/ejs.js:703:17)
    at _View._compiledSync (/home/digga/Documents/site/node_modules/hexo/lib/theme/view.js:132:24)
    at _View.renderSync (/home/digga/Documents/site/node_modules/hexo/lib/theme/view.js:59:25)
    at Object.partial (/home/digga/Documents/site/node_modules/hexo/lib/plugins/helper/partial.js:34:15)
    at eval ("/home/digga/Documents/site/themes/matery/layout/_partial/bg-cover.ejs":12:17)
    at bg-cover (/home/digga/Documents/site/node_modules/ejs/lib/ejs.js:703:17)
    at _View._compiledSync (/home/digga/Documents/site/node_modules/hexo/lib/theme/view.js:132:24)
    at _View.renderSync (/home/digga/Documents/site/node_modules/hexo/lib/theme/view.js:59:25)
    at Object.partial (/home/digga/Documents/site/node_modules/hexo/lib/plugins/helper/partial.js:34:15)
    at eval ("/home/digga/Documents/site/themes/matery/layout/archive.ejs":10:17)
    at archive (/home/digga/Documents/site/node_modules/ejs/lib/ejs.js:703:17)
    at _View._compiled (/home/digga/Documents/site/node_modules/hexo/lib/theme/view.js:136:50)
    at _View.render (/home/digga/Documents/site/node_modules/hexo/lib/theme/view.js:39:17)
    at /home/digga/Documents/site/node_modules/hexo/lib/hexo/index.js:64:21
    at tryCatcher (/home/digga/Documents/site/node_modules/bluebird/js/release/util.js:16:23)
    at /home/digga/Documents/site/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/home/digga/Documents/site/node_modules/hexo/lib/hexo/router.js:47:5)
    at Readable.read (node:internal/streams/readable:496:12)
    at resume_ (node:internal/streams/readable:999:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
ERROR 
TypeError: /home/digga/Documents/site/themes/matery/layout/archive.ejs:1
 >> 1| <%- partial('_partial/bg-cover') %>
    2| 
    3| <main class="content">
    4| 

/home/digga/Documents/site/themes/matery/layout/_partial/bg-cover.ejs:3
    1| <div class="bg-cover pd-header about-cover">
    2|     <div class="container">
 >> 3|     <%- partial('_partial/bg-cover-content') %>
    4|     </div>
    5| </div>

/home/digga/Documents/site/themes/matery/layout/_partial/bg-cover-content.ejs:46
    44| <script>
    45|     <% if (theme.banner.enable && theme.banner.random) { %>
 >> 46|       var bannerUrl = "<%- theme.cdn.url %><%- url_for('/medias/featureimages/') %>" + Math.floor(Math.random() * <%- theme.featureImages.length %>) + '.jpg';
    47|     <% } else { %>
    48|       // 每天切换 banner 图.  Switch banner image every day.
    49|       var bannerUrl = "<%- theme.cdn.url %><%- url_for('/medias/banner/') %>" + new Date().getDay() + '.jpg';

Cannot read properties of undefined (reading 'url')
    at eval ("/home/digga/Documents/site/themes/matery/layout/_partial/bg-cover-content.ejs":74:27)
    at bg-cover-content (/home/digga/Documents/site/node_modules/ejs/lib/ejs.js:703:17)
    at _View._compiledSync (/home/digga/Documents/site/node_modules/hexo/lib/theme/view.js:132:24)
    at _View.renderSync (/home/digga/Documents/site/node_modules/hexo/lib/theme/view.js:59:25)
    at Object.partial (/home/digga/Documents/site/node_modules/hexo/lib/plugins/helper/partial.js:34:15)
    at eval ("/home/digga/Documents/site/themes/matery/layout/_partial/bg-cover.ejs":12:17)
    at bg-cover (/home/digga/Documents/site/node_modules/ejs/lib/ejs.js:703:17)
    at _View._compiledSync (/home/digga/Documents/site/node_modules/hexo/lib/theme/view.js:132:24)
    at _View.renderSync (/home/digga/Documents/site/node_modules/hexo/lib/theme/view.js:59:25)
    at Object.partial (/home/digga/Documents/site/node_modules/hexo/lib/plugins/helper/partial.js:34:15)
    at eval ("/home/digga/Documents/site/themes/matery/layout/archive.ejs":10:17)
    at archive (/home/digga/Documents/site/node_modules/ejs/lib/ejs.js:703:17)
    at _View._compiled (/home/digga/Documents/site/node_modules/hexo/lib/theme/view.js:136:50)
    at _View.render (/home/digga/Documents/site/node_modules/hexo/lib/theme/view.js:39:17)
    at /home/digga/Documents/site/node_modules/hexo/lib/hexo/index.js:64:21
    at tryCatcher (/home/digga/Documents/site/node_modules/bluebird/js/release/util.js:16:23)
    at /home/digga/Documents/site/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/home/digga/Documents/site/node_modules/hexo/lib/hexo/router.js:47:5)
    at Readable.read (node:internal/streams/readable:496:12)
    at resume_ (node:internal/streams/readable:999:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
ERROR 
TypeError: /home/digga/Documents/site/themes/matery/layout/archive.ejs:1
 >> 1| <%- partial('_partial/bg-cover') %>
    2| 
    3| <main class="content">
    4|

**Comment by DeluxeLX** [comment]
我也是的兄弟，请问你解决了吗？

**Comment by ZhenzongGu** [comment]
> 我也是的兄弟，请问你解决了吗？

还没有，等大佬们回复吧

**Comment by Felixlx** [comment]
同样，，。。
/root/felix/themes/hexo-theme-matery/layout/_partial/bg-cover-content.ejs:46
    44| <script>
    45|     <% if (theme.banner.enable && theme.banner.random) { %>
 >> 46|       var bannerUrl = "<%- theme.cdn.url %><%- url_for('/medias/featureimages/') %>" + Math.floor(Math.random() * <%- theme.featureImages.length %>) + '.jpg';
    47|     <% } else { %>
    48|       // 每天切换 banner 图.  Switch banner image every day.
    49|       var bannerUrl = "<%- theme.cdn.url %><%- url_for('/medias/banner/') %>" + new Date().getDay() + '.jpg';

Cannot read properties of undefined (reading 'url')

**Comment by Felixlx** [comment]
修改了一下 46 行， 改成 var bannerUrl = "<%- theme.jsDelivr.url %><%- url_for('/medias/featureimages/') %>" + Math.floor(Math.random() * <%- theme.featureImages.length %>) + '.jpg';
    <% } else { %> 就能正常用了

**Comment by appotry** [comment]
提交了一个pr 修复这个问题 https://github.com/blinkfox/hexo-theme-matery/pull/888

**Comment by ZhenzongGu** [comment]
> 提交了一个pr 修复这个问题 #888
感谢大佬，

**Comment by ZhenzongGu** [comment]
> 修改了一下 46 行， 改成 var bannerUrl = "<%- theme.jsDelivr.url %><%- url_for('/medias/featureimages/') %>" + Math.floor(Math.random() * <%- theme.featureImages.length %>) + '.jpg'; <% } else { %> 就能正常用了

OK，那我也先本地改一下。
